cart/urls.py
from django.conf.urls import url
from .views import CartView


urlpatterns = [
    url(r'^$', CartView.as_view(), name='cart'),
]

orders/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.urls import path
from .views import AddressDetailView, prepare_order, OrderDetailView, OrderFinalizeView


urlpatterns = [
    url(r'^address/$', AddressDetailView.as_view(), name='orders_address'),
    url(r'^prepare/$', prepare_order, name='orders_prepare'),
    url(r'^overview/(?P<pk>\d+)/$', OrderDetailView.as_view(), name='orders_overview'),
    path('payment/', TemplateView.as_view(template_name='orders/payment_choose.html'), name='orders_choose_payment'),
    path('finalize/', OrderFinalizeView.as_view(), name='orders_finalize'),
]

tozd/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, password_reset, password_reset_complete, password_reset_confirm, password_reset_done
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls),
    path('shop/', include('products.urls'), name='shop'),
    path('cart/', include('cart.urls'), name='cart'),
    path('order/', include('orders.urls'), name='orders'),
    path('u/', include('users.urls', namespace='users')),
    path('zaboj/', include('zaboj.urls'), name='zaboj'),
    path('mng/', include('management.urls'), name='management'),

    path('logout/', LogoutView.as_view(template_name='users/logout.html', next_page='/'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('password_reset/', password_reset, name='password_reset'),
    path('password_reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', password_reset_complete, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
from django.db import models
from tozd.settings import AUTH_USER_MODEL as User
from users.models import Distributer


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    subtotal = models.DecimalField(decimal_places=2, max_digits=8)
    tax_total = models.DecimalField(decimal_places=2, max_digits=8)
    total = models.DecimalField(decimal_places=2, max_digits=8)
    discount_for_returned_package = models.DecimalField(decimal_places=2, max_digits=8)
    to_pay = models.DecimalField(decimal_places=2, max_digits=8)
    delivery_method = models.PositiveIntegerField()
    comment = models.TextField(blank=True, null=True)
    payment_method = models.IntegerField(choices=((1, "Gotovina"), (2, "Predračun"), (3, "Predplačilo")), default=2)
    distributer = models.ForeignKey(Distributer, on_delete=models.SET_NULL, null=True)
    finalized = models.BooleanField(default=False)
    processed = models.BooleanField(default=False)
    shipped = models.BooleanField(default=False)
    arrived = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} ({self.created})'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=120)
    item_price = models.DecimalField(decimal_places=2, max_digits=8)
    item_quantity = models.PositiveIntegerField(blank=True, null=True)
    item_decimal_quantity = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True)
    item_unit_of_measure = models.CharField(max_length=20, blank=True, null=True)
    item_tax_bracket = models.DecimalField(decimal_places=2, max_digits=4)
    item_subtotal = models.DecimalField(decimal_places=2, max_digits=8)
    item_tax_total = models.DecimalField(decimal_places=2, max_digits=8)
    item_total = models.DecimalField(decimal_places=2, max_digits=8)
    item_package = models.CharField(max_length=120, blank=True, null=True)
    item_package_price = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True)
    item_package_subtotal = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True)
    item_package_tax_total = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True)
    item_package_total = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True)

    def __str__(self):
        return f'{self.order}: {self.item_name}'


class OrderBillingAddress(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    surname = models.CharField(max_length=120)
    street_name = models.CharField(max_length=120)
    street_nr = models.CharField(max_length=10)
    zip_code = models.PositiveIntegerField()
    city = models.CharField(max_length=120)
    country = models.CharField(max_length=120)
    company_name = models.CharField(max_length=120, blank=True, null=True)
    vat_nr = models.PositiveIntegerField(blank=True, null=True)
    vat_taxpayer = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} {self.surname}, {self.street_name} {self.street_nr}'

class OrderShippingAddress(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    surname = models.CharField(max_length=120)
    street_name = models.CharField(max_length=120)
    street_nr = models.CharField(max_length=10)
    zip_code = models.PositiveIntegerField()
    city = models.CharField(max_length=120)
    country = models.CharField(max_length=120)

    def __str__(self):
        return f'{self.name} {self.surname}, {self.street_name} {self.street_nr}'

users/models.py
""" Models for the users app. """
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

class User(AbstractUser):
    """
    Extending the default User model.
    Iz registra:
    IME	PRIIMEK	    REGIJA	    KRAJ	    SKUPNOST
    NASLOV	        MAIL	    TELEFON	    VEZA
    PREVZEMNI REŽIM	ROTACIJA_K	ROTACIJA_Z	ČLAN
    """
    phone_re = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                              message='Telefonska mora biti v formatu "+999999999". \
                                       Dovoljenih do 15 znakov.')

    address = models.CharField(max_length=120, blank=True, null=True,
                               help_text='Ulica in hišna številka.')
    city = models.CharField(max_length=50, blank=True, null=True,
                            help_text='Ime kraja (brez poštne številke).')
    district = models.CharField(max_length=50, blank=True, null=True,
                                help_text='Ime četrtne skupnosti (npr. "Bežigrad"). Lahko prazno.')
    phone_nr = models.CharField(max_length=15, validators=[phone_re], blank=True, null=True,
                                help_text='Format: +38611111111')
    pickup_method = models.IntegerField(choices=[(1, 'Dostava na dom'),
                                                 (2, 'Prevzem pri distributerju'),
                                                 (3, 'Leteči')],
                                        help_text='1. Dostavmo na dom (+1€). \
                                                   2. Prevzem v svoji četrti/kraju. \
                                                   3. Prevzem na poti po dogovoru z distributerjem.'
                                        , null=True)
    is_union_member = models.BooleanField(default=False)
    likes = models.ManyToManyField('zaboj.Vegetable', related_name='%(class)s_likes')
    dislikes = models.ManyToManyField('zaboj.Vegetable', related_name='%(class)s_dislikes')

    def get_absolute_url(self):
        """ Redirect after edit. """
        return '/u/me'

    def __str__(self):
        return f'{self.last_name}, {self.first_name} ({self.username})'

class UserBillingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    surname = models.CharField(max_length=120)
    street_name = models.CharField(max_length=120)
    street_nr = models.CharField(max_length=10)
    zip_code = models.PositiveIntegerField()
    city = models.CharField(max_length=120)
    country = models.CharField(max_length=120)
    vat_nr = models.PositiveIntegerField(blank=True, null=True)
    vat_taxpayer = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} {self.surname}, {self.street_name} {self.street_nr}'

class UserShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    surname = models.CharField(max_length=120)
    street_name = models.CharField(max_length=120)
    street_nr = models.CharField(max_length=10)
    zip_code = models.PositiveIntegerField()
    city = models.CharField(max_length=120)
    country = models.CharField(max_length=120)

    def __str__(self):
        return f'{self.name} {self.surname}, {self.street_name} {self.street_nr}'

class Distributer(models.Model):
    """
    Model for the distributers. Fields:
    USER (User)    DISTRICT (Char)    MAIN (Bool)
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    district = models.CharField(max_length=50, blank=True, null=True)
    main = models.BooleanField()

    def __str__(self):
        return str(self.user) + " (" + str(self.district) + ")"

orders/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView

from cart.models import Cart, CartItem
from products.models import Variation
from .models import Order, OrderItem, OrderBillingAddress, OrderShippingAddress
from users.models import User, UserBillingAddress, UserShippingAddress, Distributer
from users.forms import UserBillingAddressForm, UserShippingAddressForm, UserPickupMethodForm

class AddressDetailView(FormView, DetailView):
    model = User
    template_name = 'orders/address_detail.html'
    form_class = UserPickupMethodForm

    def get_context_data(self, **kwargs):
        context = super(AddressDetailView, self).get_context_data(**kwargs)
        context['billing_form'] = UserBillingAddressForm()
        context['shipping_form'] = UserShippingAddressForm()
        context['distributers'] = Distributer.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('form-type') == 'billing':
            form = UserBillingAddressForm(request.POST)
        else:
            form = UserShippingAddressForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
        if request.POST.get('copy-address') == 'on':
            form2 = UserShippingAddressForm(request.POST)
            if form2.is_valid():
                obj = form2.save(commit=False)
                obj.user = request.user
                obj.save()
        return HttpResponseRedirect(self.request.path_info)

    def get_object(self):
        """ get object from model class """
        return get_object_or_404(User, pk__iexact=self.request.user.id)

    def get_form_kwargs(self):
        kw = super(AddressDetailView, self).get_form_kwargs()
        kw['request'] = self.request
        return kw

def prepare_order(request):
    """
    Prepare the order and return the overview page to confirm order.
    Request looks like: ?distributer=2&bill_addr=1
    """
    distributer_id = request.GET.get('distributer')
    billing_address_id = request.GET.get('bill_addr')
    pickup_method = 2 # this is left in place if we ever decide to have door-to-door deliveries - otherwise it should be deleted
    cart = Cart.objects.get_or_create(user=request.user, processed_to_order=False)[0]
    user_bill_addr = UserBillingAddress.objects.get_or_create(pk=billing_address_id, user=request.user)[0]
    distributer = Distributer.objects.get(pk=distributer_id)

    # Create order
    order = Order()
    order.user = request.user
    order.distributer = distributer
    order.subtotal = cart.subtotal
    order.tax_total = cart.tax_total
    order.total = cart.total
    order.discount_for_returned_package = 0 #TODO implement returned packaging
    order.to_pay = 0 #TODO implement returned packaging
    order.delivery_method = pickup_method
    order.save()

    # create all order items
    for item in cart.cartitem_set.all():
        order_item = OrderItem()
        order_item.order = order
        order_item.item_name = str(item.item)
        order_item.item_price = item.item.price
        order_item.item_quantity = item.quantity
        order_item.item_decimal_quantity = 0 #TODO implement decimal quantity
        order_item.item_unit_of_measure = "kom" #TODO implement decimal quantity
        order_item.item_tax_bracket = item.item.tax_bracket
        order_item.item_subtotal = item.line_subtotal
        order_item.item_tax_total = item.line_tax_total
        order_item.item_total = item.line_tax_total
        if item.item.package_type == None:
             order_item.item_package = None
             order_item.item_package_price = 0
        else:
            order_item.item_package = item.item.package_type.type
            order_item.item_package_price = item.item.package_type.price
        order_item.item_package_subtotal = item.line_package_subtotal
        order_item.item_package_tax_total = item.line_package_tax_total
        order_item.item_package_total = item.line_package_total
        order_item.save()

    billing_address = OrderBillingAddress()
    billing_address.order = order
    billing_address.name = user_bill_addr.name
    billing_address.surname = user_bill_addr.surname
    billing_address.street_name = user_bill_addr.street_name
    billing_address.street_nr = user_bill_addr.street_nr
    billing_address.zip_code = user_bill_addr.zip_code
    billing_address.city = user_bill_addr.city
    billing_address.country = user_bill_addr.country
    billing_address.vat_nr = user_bill_addr.vat_nr
    billing_address.vat_taxpayer = user_bill_addr.vat_taxpayer
    billing_address.save()

    return redirect(reverse('orders_overview', kwargs={'pk': str(order.pk)}))

class OrderDetailView(DetailView):
    model = Order

    def post(self, request, *args, **kwargs):
        comment = request.POST.get('comment')
        order = self.get_object()
        order.comment = comment
        order.save()
        return HttpResponse(status=200)


class OrderFinalizeView(TemplateView):
    template_name = 'orders/finalze.html'

    def get(self, request, *args, **kwargs):
        payment_method = request.GET.get('method')
        order = Order.objects.filter(user=request.user).last()
        print(order)
        order.payment_method = payment_method
        order.save()

        cart = Cart.objects.get(processed_to_order=False, user=request.user)
        cart.processed_to_order = True
        cart.save()
        return super(OrderFinalizeView, self).get(request, *args, **kwargs)

orders/templates/orders/address_detail.html
{% extends "base.html" %}

{% block head_title %}Pregled naslova za dostavo in izdajo računa || {{ block.super }}{% endblock head_title %}


{% block content %}
{% load crispy_forms_tags %}

<div class="alert alert-danger" role="alert">
        <span id="alert-msg"></span>
    </div>

<h3>Izberi prevzemno mesto</h3>

{%for distributer in distributers %}
<div class="radio">
    <label>
        <input type="radio" name="distributer-radio" value="{{ distributer.pk }}">
        {{distributer.user.address}} {% if distributer.user.district %} ({{ distributer.user.district }}) {% endif %}, {{distributer.user.city}}
    </label>
    </div>
{% endfor %}
<br>

<h3>Naslov za račun</h3>
{% if object.userbillingaddress_set.count == 0 %}
<p>Nimate naslova za izdajo računa. Dodaj nov naslov.</p>

{% else %}
{% for address in object.userbillingaddress_set.all %}
<div class="radio">
    <label>
        <input type="radio" name="billing-radio" value="{{ address.pk }}"> {{ address.name}} {{ address.surname}} - 
        {{ address.street_name}} {{ address.street_nr}}, {{ address.zip_code}} {{ address.city}} 
        {% if address.vat_nr %}
        (Davčni zavezanec: {% if address.vat_taxpayer %} Da {% else %} Ne {% endif %}, davčna: {{ address.vat_nr }} )
        {% endif %}
    </label>
</div>
{% endfor %}
{% endif %}

<!-- Modal -->
<div class="modal fade" id="billingModal" tabindex="-1" role="dialog" aria-labelledby="billingModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Dodaj naslov za izdajo računa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action="{% url 'orders_address' %}" method="post">
                <div class="modal-body">
                <input type="hidden" name="form-type" value="billing">
                {% csrf_token %}
                {{ billing_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zapri</button>
                    <button type="submitt" class="btn btn-primary">Shrani spremembe</button>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#billingModal">
    Dodaj nov naslov za račun
</button>

<br>
<br>
<table class="table">
    <tr>
        <td colspan='6' class='text-right'>
            <a class='btn btn-secondary' href="{% url 'cart' %}">Nazaj na košarico</a>
            <a class='btn btn-warning' id ="next-step" href="#">Naprej na pregled naročila</a>
        </td>
    </tr>
</table>

{% endblock content %}

{% block jquery %}
$(".alert").hide();
$("#next-step").click(function(){
    var distributer = $("input[name=distributer-radio]:checked").val()
    console.log(distributer)
    var billing = $("input[name=billing-radio]:checked").val()
    if (distributer && billing) {
        url = "{% url 'orders_prepare' %}?distributer=" + distributer + "&bill_addr=" + billing
        window.location.replace(url)
    }
    else {
        $("#alert-msg").text("Izberi naslov za prevzem in izdajo računa.");
        if (distributer) $("#alert-msg").text("Izberi naslov za izdajo računa.");
        if (billing) $("#alert-msg").text("Izberi naslov za prevzem.");
        $(".alert").show()
    }
})

{% endblock jquery %}

orders/templates/orders/finalize.html
{% extends "base.html" %}

{% block head_title %}Pregled naslova za dostavo in izdajo računa || {{ block.super }}{% endblock head_title %}


{% block content %}

<h3>Vaše naročilo je oddano</h3>

<p>Dodatne podrobnosti vam pošljemo po e-pošti. To stran lahko zaprete.</p>

{% endblock content %}

orders/templates/orders/order_detail.html
{% extends "base.html" %}

{% block head_title %}Pregled naročila || {{ block.super }}{% endblock head_title %}



{% block content %}

<div class='row main-content'>
    <div class="col-sm-6 col-sm-offset-2 border border-light rounded" style="padding:30px;">
        <h2>Naslov za izdajo računa</h2>
        {% for addr in order.orderbillingaddress_set.all %}
            <strong>{{ addr.name }} {{ addr.surname }}</strong><br>
            {{ addr.street_name }} {{ addr.street_nr }} <br>
            {{ addr.zip_code }} {{ addr.city }} <br>
            {{ addr.country }} <br>
            {% if addr.vat_nr %}
                Podjetje: {{ addr.company_name }} <br>
                Davčna številka: {{ addr.vat_nr }} <br>
                {% if addr.vat_taxpayer %}
                Davčni zavezanec: Da
                {% else %}
                Davčni zavezanec: Ne
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <div class="col-sm-6 col-sm-offset-2 border border-light rounded" style="padding:30px;">
        <h2>Naslov za prevzem</h2>
        {{ order.distributer.user.address }}  {% if order.distributer.user.district %} ({{ order.distributer.user.district }}) {% endif %}<br>
        {{ order.distributer.user.city }}
    </div>

    <div class='col-sm-12 col-sm-offset-2'>
    <br>
    <hr>
    <h2>Opombe:</h2>
    <div id="comment">{% if order.comment %} {{ order.comment|linebreaks }} {% endif %}</div><br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Dodaj/popravi opombo
    </button>
    <br>
    <hr>
    <h2>Pregled naročila</h2>
    <table class='table'> 
        <tr id='item-{{ item.item.id }}'>
            <td>Ime izdelka</td>
            <td>Količina</td>
            <td>Cena/kos</td>
            <td>Cena brez DDV</td>
            <td>DDV</td>
            <td>Cena</td>
        </tr>
    
        {% for item in order.orderitem_set.all %}
        
        <tr>
            <td>{{ item.item_name }}</td>
            <td>{{ item.item_quantity }}</td>
            <td>{{ item.item_price|floatformat:2 }}€</td>
            <td>{{ item.item_subtotal|floatformat:2 }}€</td>
            <td>{{ item.item_tax_total|floatformat:2 }}€</td>
            <td>{{ item.item_total|floatformat:2 }}€</td>
        </tr>
        {% if item.item_package %}
        <tr>
            <td><i class="fas fa-caret-right" style="margin-left:1em;"></i> Embalaža: {{ item.item_package }}</td>
            <td>{{ item.item_quantity }}</td>
            <td>{{ item.item_package_price }}€</td>
            <td>{{ item.item_package_subtotal|floatformat:2 }}€</td>
            <td>{{ item.item_package_tax_total|floatformat:2 }}€</td>
            <td>{{ item.item_package_total|floatformat:2 }}€</td>
        </tr>
        {% endif %}
        {% endfor %}
        
        <tr>
            <td  colspan='5' class='text-right'>Skupaj brez DDV</td>
            <td>{{ order.subtotal|floatformat:2 }}€</td>
        </tr>
        
        <tr>
            <td colspan='5' class='text-right'>DDV</td>
            <td>{{ order.tax_total|floatformat:2 }}€</td>
        </tr>
        
        <tr>
            <td colspan='5' class='text-right'>Skupaj</td>
            <td>{{ order.total|floatformat:2 }}€</td>
        </tr>

        <tr>
            <td  colspan='5' class='text-right'>Vrnjene embalaže</td>
            <td>Obračunano naknadno {# order.discount_for_returned_package|floatformat:2 #}</td>
        </tr>

        <tr>
            <td colspan='5' class='text-right'>Za plačilo</td>
            <td>Obračunano naknadno {# order.to_pay|floatformat:2 #}</td>
        </tr>
        
        
        <tr>
            <td colspan='6' class='text-right'>
                <a class='btn btn-secondary' href="{% url 'orders_address' %}">Nazaj na izbiro naslova</a>
                <a class='btn btn-warning' href="{% url 'orders_choose_payment' %}">Na plačilo</a></td>
        </tr>
        
    </table>
    
    
    </div>
    
    </div>
      
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Dodaj opombo</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form method="post" id="add-comment" action=".">{% csrf_token %}
                <div class="modal-body">  
                    <textarea name="comment" rows="5" style="width: 100%;" id="comment-txtbox">{% if order.comment %} {{ order.comment }} {% endif %}</textarea>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" value="Dodaj opombo">
                </div>
            </form>
          </div>
        </div>
      </div>
{% endblock %}

    {% block jquery %}
    $( "#add-comment" ).submit(function( event ) {
        event.preventDefault();
        $.ajax({
            data: $(this).serialize(),
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            success: function(response) {
                comment = $("#comment-txtbox").val().replace(/\n/gi,'<br />');
                $("#comment").empty().html(comment);
                $('#exampleModal').modal('toggle');
            }
        });
        return false;
    });
    {% endblock %}

orders/templates/orders/payment_choose.html
{% extends "base.html" %}

{% block head_title %}Izbira načina plačila || {{ block.super }}{% endblock head_title %}


{% block content %}
<h1>Izberi način plačila:</h1><br>
<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Plačilo po predračunu</h5>
                <p class="card-text">Plačaj po predračunu preko spletne banke (UPN).</p>
                <a href="{% url 'orders_finalize' %}?method=2" class="btn btn-primary">Izberi plačilo po predračunu</a>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="collapse" id="collapseOther">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Plačilo po prevzetju</h5>
                    <p class="card-text">Plačaš z gotovino distributerju ob prevzemu naročila.</p>
                    <a href="{% url 'orders_finalize' %}?method=1" class="btn btn-primary">Izberi plačilo po prevzetju</a>
                </div>
            </div>
        </div>
    </div>
    <!--
        <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Naloži sredstva</h5>
                <p class="card-text">Naloži sredstva vnaprej. Ob nakazilu min. 20€ ti pripada 10% bonus.</p>
                <a href="{% url 'orders_finalize' %}?method=3" class="btn btn-primary">Naloži sredstva in pridobi bonus</a>
            </div>
        </div>
    </div>
    -->
</div>
<br>
<br>
<div class="row">
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseOther" role="button" aria-expanded="false" aria-controls="collapseOther">
        Prikaži druge načine plačila
    </a>
</div>

{% endblock content %}