cart/urls.py
from django.conf.urls import url
from .views import CartView


urlpatterns = [
    url(r'^$', CartView.as_view(), name='cart'),
]

tozd/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, password_reset, password_reset_complete, password_reset_confirm, password_reset_done
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls),
    path('shop/', include('products.urls'), name='shop'),
    path('cart/', include('cart.urls'), name='cart'),
    path('order/', include('orders.urls'), name='orders'),
    path('u/', include('users.urls', namespace='users')),
    path('zaboj/', include('zaboj.urls'), name='zaboj'),
    path('mng/', include('management.urls'), name='management'),

    path('logout/', LogoutView.as_view(template_name='users/logout.html', next_page='/'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('password_reset/', password_reset, name='password_reset'),
    path('password_reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', password_reset_complete, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import re_path, path
from .views import UserHome, UserEdit, SignUpView, test_view, EditPreferences


app_name = 'users'
urlpatterns = [
    path('edit/', UserEdit.as_view(), name='edit'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('preferences/', EditPreferences.as_view(), name='preferences'),
    re_path(r'^(?P<username>[.+@_\w-]+)/$', UserHome.as_view(), name='home'),
    re_path(r'^test/(?P<ttt>[.+@_\w-]+)/$', test_view, name='test'),
    
]

tozd/templates/base.html
<!DOCTYPE html>
<html lang=en>

<head>
<title>{% block head_title %}NDP TOZD{% endblock head_title %}</title>
{% include 'snippets/css.html' %}
</head>
<body>
{% include 'snippets/nav.html' %}

<div class='container'>
{% block content %}
{% endblock content %}
</div>


{% include 'snippets/js.html' %}


<script>
$(document).ready(function() {
	var pathname = window.location.pathname;
    $('.nav-item.active').removeClass('active');
	$('.nav-item > a[href="'+pathname+'"]').parent().addClass('active');
    if ($("#item-count").text() != 0) {
        $("#item-count").removeClass("invisible");
    }
    {% block jquery %}
    {% endblock jquery %}
});
</script>

</body>
</html>

tozd/templates/index.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'login' %}">Login</a> or <a href="{% url 'users:signup' %}">Signup</a><br /><br />

Oglej in uredi svoj <a href="{% url 'users:home' username='me' %}">profil</a><br /><br />

Oddaj <a href="{% url 'order' %}">naročilo</a>

{% endblock %}