cart/urls.py
from django.conf.urls import url
from .views import CartView


urlpatterns = [
    url(r'^$', CartView.as_view(), name='cart'),
]

products/urls.py
from django.conf.urls import url
from .views import ProductDetailView, ProductListView


urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='product_list'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
]

tozd/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, password_reset, password_reset_complete, password_reset_confirm, password_reset_done
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls),
    path('shop/', include('products.urls'), name='shop'),
    path('cart/', include('cart.urls'), name='cart'),
    path('order/', include('orders.urls'), name='orders'),
    path('u/', include('users.urls', namespace='users')),
    path('zaboj/', include('zaboj.urls'), name='zaboj'),
    path('mng/', include('management.urls'), name='management'),

    path('logout/', LogoutView.as_view(template_name='users/logout.html', next_page='/'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('password_reset/', password_reset, name='password_reset'),
    path('password_reset/done/', password_reset_done, name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', password_reset_complete, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify

from management.models import PackageType

class ProductQueryset(models.query.QuerySet):
    """
    queryset to filter out inactive products and variations
    """
    def active(self):
        return self.filter(active=True)

class ProductManager(models.Manager):
    """
    a model manager thet lets us set the default queryset
    """
    def get_queryset(self):
        return ProductQueryset(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

class ProductOption(models.Model):
    """
    Options on a model, like "red", "250 g", etc.
    """
    display_name = models.CharField(max_length=120)
    varbose_name = models.CharField(max_length=120)

    def __str__(self):
        return self.varbose_name

class ProductOptionGroup(models.Model):
    """
    Option groups, like: "color", "size", etc.
    """
    display_name = models.CharField(max_length=120)
    varbose_name = models.CharField(max_length=120)
    options = models.ManyToManyField(ProductOption, db_constraint=False)

    def __str__(self):
        return self.varbose_name

class Product(models.Model):
    """
    Model for products.
    """
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    tax_bracket = models.DecimalField(decimal_places=2, max_digits=4, default="22")
    active = models.BooleanField(default=True)
    package_type = models.ForeignKey(PackageType, on_delete=models.CASCADE, null=True, blank=True)
    option_groups = models.ManyToManyField(ProductOptionGroup)

    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.pk)])

class Variation(models.Model):
    """
    Model for product variations.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    options = models.ManyToManyField(ProductOption)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    tax_bracket = models.DecimalField(decimal_places=2, max_digits=4, default="22")
    active = models.BooleanField(default=True)
    inventory = models.PositiveIntegerField(null=True, blank=True)
    package_type = models.ForeignKey(PackageType, on_delete=models.CASCADE, null=True, blank=True)

    objects = ProductManager()

    def __str__(self):
        if self.title == "Default":
            return self.product.title
        return f'{self.product.title} - {self.title}'

    def get_absolute_url(self):
        """
        returns the absolute URL of the product - variations can't "live" on their own
        """
        return self.product.get_absolute_url

@receiver(post_save, sender=Product)
def create_default_variation(instance, **kwargs):
    """
    When the instance of a Product is saved we should check if a variation exists.
    If not, we should create one with the title "Default".
    """
    if instance.variation_set.count() == 0:
        default_variation = Variation()
        default_variation.product = instance
        default_variation.title = "Default"
        default_variation.description = instance.description
        default_variation.price = instance.price
        default_variation.active = instance.active
        default_variation.package_type = instance.package_type
        default_variation.save()

def image_upload_to(instance, filename):
    print(instance.id)
    title = instance.product.title
    slug = slugify(title)
    basename, file_extension = filename.split(".")
    new_filename = f'{slug}.{file_extension}'
    return f'products/{slug}/{new_filename}'

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload_to)
    
    def __str__(self):
        return self.product.title

class VariationImage(models.Model):
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload_to)
    
    def __str__(self):
        return self.variation.title

products/views.py
"""
Views for products -> store.
"""

from django.http import JsonResponse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Product, Variation

class ProductDetailView(DetailView):
    model = Product

    def get(self, request, **kwargs):
        if request.is_ajax():
            product = request.GET.get('product')
            options = request.GET.get('options', '').split(',')
            queryset = Variation.objects.filter(product=product)
            for option in options:
                queryset = queryset.filter(options=option)
            if not queryset.exists():
                return JsonResponse({"message": "Kombinacija ne obstaja."})
            if queryset.count() > 1:
                return JsonResponse({"message": "Izdelek ni unikatno določen z izbranimi opcijami."})
            variation = queryset.first()
            if not variation.active:
                return JsonResponse({"message": "Kombinacija ni aktivna."})
            data = {
                "message": "Izdelek uspešno najden.",
                "id": variation.pk,
                "price": variation.price,
            }
            return JsonResponse(data)
        else:
            return super(ProductDetailView, self).get(request, **kwargs)

class ProductListView(ListView):
    model = Product

products/templates/products/product_detail.html
{% extends "base.html" %}

{% block head_title %}Pregled izdelka || {{ block.super }}{% endblock head_title %}


{% block content %}
<div class="container" style="width:100%">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p id="alert-message"></p>
    </div>
</div>
<div class="row">
    <div class="col-8">
        <div>
            {% if product.productimage_set.count > 0 %}
                {% for image in product.productimage_set.all %}
                <img class="img-fluid" src="{{ image.image.url }}" alt="{{ product.title }}">
                {% endfor %}
            {% endif %}
        </div>
        <h2>{{ product.title }}</h2>
        <P>{{ product.description }}</P>
    </div>
    <!-- Stranska vrstica - produkt -->
    <div class="col-4">
            {% if product.variation_set.count > 1 %}
            <h3 id="price">{{ product.price }}€</h3><span class="zaloga"></span><br>
            {% for group in product.option_groups.all %}
                <h4>{{ group.display_name }}</h4>
                <select name="{{ group.display_name }}" class="form-control" id="select-variation-{{ group.pk }}">
                <option value="">-----</option>
                {% for option in group.options.all %}
                    <option value="{{ option.pk }}">{{ option.display_name }}</option>
                {% endfor %}
                </select><br>
            {% endfor %}
            <input type="hidden" id="variation" value="">
            {% else %}
            <h3 id="price">{{ product.price }}€</h3>
            <input type="hidden" id="variation" value="{{ product.variation_set.first.id }}">
            {% endif %}
            <br>
            <input class="form-control" type="number" value="1" id="qty" />
            <br>
            <input type="submit" id="add-cart" class="btn btn-default" value="Add to cart">
        <hr>
        <h6>Drugi so kupili še:</h6>
    </div>    
    <!-- End Stranska vrstica - produkt -->
</div>

{% endblock %}

{% block jquery %}
    $(".alert").hide()
    $("[id^=select-variation]").change(function(){
        var options=[]
        $("[id^=select-variation]").each(function(){
            if (this.value) options.push(this.value);
        });
        $.ajax({
            type: "GET",
            url: "?product={{ product.pk }}&options=" + options.toString(),
            success: function (response) {
                if (response.id) {
                    $("#price").text(response.price + "€");
                    $("#variation").val(response.id);
                }
            },
            error: function (response) {
              alert(response.status);
            }
        });
    });
    $("#add-cart").click(function(){
        var item = $("#variation").val();
        if (item == "") {
            alert("Izdelek ni na zalogi ali ne obstaja.")
            return false;
        }
        var qty = $("#qty").val();
        $.ajax({
            type: "GET",
            url: "{% url 'cart' %}?item=" + item + "&qty=" + qty,
            success: function (response) {
                $("#alert-message").text(response.message);
                $(".alert").show();
                window.setTimeout(function () { 
                    $(".alert").hide("slow"); }, 2000);
                $("#item-count").text(response.itemCount)
                $("#item-count").removeClass("invisible");
            },
            error: function (response) {
              alert(response.status);
            }
          });
    })
{% endblock jquery %}

products/templates/products/product_list.html
{% extends "base.html" %}

{% block head_title %}TOZD trgovina || {{ block.super }}{% endblock head_title %}


{% block content %}
<div class="card-columns">
    {% for product in product_list %}
    <a href="{{ product.get_absolute_url }}" style="text-decoration: none; color:black;">
        <div class="card">
            <img class="card-img-top" src="{{ product.productimage_set.first.image.url }}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description|truncatechars:150 }}</p>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}

products/templates/products/products.html
<div class='row'>
    {% for product in object_list %}
        <div class='col-xs-4 {{ col_class_set }}'>
            {{ product.title }}
        </div>
        {% if not col_class_set %}
    {% cycle '' '' '</div><div class="row">' %}
    {% endif %}
    {% endfor %}